version: "3.9"

services:
  db:
    image: postgres:15
    container_name: keycloak_db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: keycloak_test
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: info
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "5001:8080"
    depends_on:
      - db

volumes:
  keycloak_postgres_data:
